language: node_js

node_js: node

services: 
  - docker

before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - 

install:
 - npm i

script: 
 - npm test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

