version: "3.7"

services:
  simple-node-docker:
    image: jppanda/test:simple-node-demo  #Replace with your docker image name
    ports:
      - "80:3000"
    deploy:
      restart_policy:
        condition: on-failure
