version: "3.7"

services:
  simple-node-docker:
    image: sharks-node-demo:latest  #Replace with your docker image name
    ports:
      - "80:3000"
    deploy:
      restart_policy:
        condition: on-failure
